global:
  resolve_timeout: 30s

route:
  receiver: mission-alert-receiver
  group_by: [ 'alertname', 'userId' ]
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: mission-alert-receiver
    webhook_configs:
      - url: 'http://inventory-service:8080/api/alerts'